<?php
use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../src/functions/menu.php';

/**
 * Tests the menu data and HTML output.
 *
 * The tests cover JSON loading, invalid files, required item fields,
 * nested menu levels, and the HTML generated by renderMenu().
 *
 * @author Livia Pérez Bettero
 */
class MenuTest extends TestCase
{
    private string $menuPath;

    /**
     * Set the menu JSON path before each test.
     */
    protected function setUp(): void
    {
        $this->menuPath = __DIR__ . '/../public/assets/data/menu.json';
    }

    /**
     * Check that the menu JSON file exists.
     */
    public function testMenuJsonExiste(): void
    {
        $this->assertFileExists(
            $this->menuPath,
            "❌ El archivo menu.json no existe en la ruta esperada: {$this->menuPath}"
        );
    }

    /**
     * Check that the menu JSON is valid.
     */
    public function testMenuJsonValido(): void
    {
        $json = @file_get_contents($this->menuPath);
        $this->assertNotFalse($json, "❌ No se pudo leer el archivo menu.json.");

        $data = json_decode($json, true);
        $this->assertIsArray($data, "❌ El JSON no decodificó a un array válido.");
        $this->assertNotEmpty($data, "⚠️ El menú JSON existe pero está vacío o sin elementos.");
    }

    /**
     * Check that getMenuData() returns the expected data.
     */
    public function testGetMenuDataFuncionaCorrectamente(): void
    {
        $data = getMenuData($this->menuPath);
        $this->assertIsArray($data, "❌ getMenuData() no devolvió un array.");

        $this->assertArrayHasKey(
            'title', 
            $data[0] ?? ['title' => null], 
            "❌ Los elementos del menú deberían contener una clave 'title'."
        );
    }

    /**
     * Check that getMenuData() handles missing files.
     */
    public function testMenuDataArchivoInexistente(): void
    {
        $resultado = getMenuData(__DIR__ . '/no_existe.json');
        $this->assertIsArray($resultado, "❌ getMenuData() no devolvió un array al faltar el archivo.");
        $this->assertArrayHasKey('error', $resultado, "⚠️ No se generó un mensaje de error al faltar el archivo.");
    }

    /**
     * Check that getMenuData() handles invalid JSON.
     */
    public function testMenuDataJsonInvalido(): void
    {
        $tempFile = tempnam(sys_get_temp_dir(), 'menu');
        file_put_contents($tempFile, '{ "invalid_json": [ '); // Incomplete JSON

        $resultado = getMenuData($tempFile);
        unlink($tempFile);

        $this->assertIsArray($resultado, "❌ La función no devolvió un array ante un JSON inválido.");
        $this->assertArrayHasKey('error', $resultado, "⚠️ Se esperaba una clave 'error' al procesar JSON inválido.");
    }

    /**
     * Check that renderMenu() returns valid menu HTML.
     */
    public function testRenderMenuGeneraHtml(): void
    {
        // Check that the function exists before calling it.
        $this->assertTrue(function_exists('renderMenu'), "❌ La función renderMenu() no está definida.");

        ob_start();
        renderMenu();
        $output = ob_get_clean();

        $this->assertIsString($output, "❌ El contenido renderizado no es una cadena de texto.");
        $this->assertNotEmpty(trim($output), "⚠️ renderMenu() no generó contenido HTML.");

        // Accept the supported menu containers.
        $containsNav = str_contains($output, '<nav');
        $containsList = str_contains($output, '<ul') || str_contains($output, '<div');

        $this->assertTrue(
            $containsNav || $containsList,
            "❌ La salida no contiene una estructura HTML reconocible (<nav>, <ul> o <div>)."
        );

        $this->assertMatchesRegularExpression(
            '/<a[^>]+href=|x-data|x-show/i',
            $output,
            "⚠️ El HTML del menú no contiene enlaces ni atributos de AlpineJS esperados."
        );
    }

    /**
     * Check the required fields in each menu item.
     */
    public function testEstructuraDeItems(): void
    {
        $data = getMenuData($this->menuPath);
        $this->assertIsArray($data, "❌ El menú no devolvió una estructura válida para su análisis.");

        $validateItem = function ($item) use (&$validateItem) {
            $this->assertArrayHasKey('title', $item, "❌ Falta la clave 'title' en un elemento del menú.");

            if (isset($item['children'])) {
                $this->assertIsArray(
                    $item['children'],
                    "❌ El campo 'children' debe ser un array si está presente en '{$item['title']}'."
                );

                // Check nested items recursively.
                foreach ($item['children'] as $child) {
                    $validateItem($child);
                }
            }
        };

        foreach ($data as $item) {
            $validateItem($item);
        }
    }


    /**
     * Check that the menu contains at least one nested level.
     */
    public function testMenuTieneSubniveles(): void
    {
        $data = getMenuData($this->menuPath);
        $hasNested = false;

        foreach ($data as $item) {
            if (!empty($item['children'])) {
                $hasNested = true;
                break;
            }
        }

        $this->assertTrue($hasNested, "⚠️ El menú JSON no contiene niveles secundarios (children vacíos).");
    }
}
